### ISSUE TITLE
[Bug] dataprep/retriever is not working as expected in ChatQnA with Qdrant

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIExamples#1473]
### Priority

P2 - High

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [x] Pull docker images from hub.docker.com
- [ ] Build docker images from source
- [ ] Other

### Deploy method

- [ ] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Kubernetes GMC
- [ ] Other

### Running nodes

Single Node

### What's the version?

git commit ed16308

### Description

When launch ChatQnA with Qdran vector DB, after successfully uploading the document, we can not retrieve the previously uploaded document. The return of the retriever is always containing 0 document, not as what we've expected.

The retrieval result is:

{"id":"6d08404f2c77900d78baeb58bbb97d6c","retrieved_docs":[],"initial_query":"What is the revenue of Nike in 2023?","top_n":1,"metadata":[]}

Expected result should be something valid docs in the field `retrieved_docs`.

Checking the qdrant-vector-db log, finding that dataprep and retriever are not using the same collection in Qdrant.

### Reproduce steps

cd GenAIExamples/ChatQnA/docker_compose/intel/cpu/xeon
source ./set_env.sh
docker compose -f compose_qdrant.yaml up

# upload the document
curl http://localhost:6043/v1/dataprep/ingest -X POST -H "Content-Type: multipart/form-data" -F "files=@./nike.txt"

# retrieve the document
export your_embedding=$(python3 -c "import random; embedding = [random.uniform(-1, 1) for _ in range(768)]; print(embedding)") 
curl http://localhost:6045/v1/retrieval -X POST -H 'Content-Type: application/json' -d "{\"text\":\"What is the revenue of Nike in 2023?\",\"embedding\":${your_embedding}}"

### Raw log

```shell
docker compose -f compose_qdrant.yaml logs qdrant-vector-db

qdrant-vector-db  | 2025-01-26T08:27:08.808448Z  INFO actix_server::builder: Starting 151 workers
qdrant-vector-db  | 2025-01-26T08:27:08.808458Z  INFO actix_server::server: Actix runtime found; starting in Actix runtime
qdrant-vector-db  | 2025-01-26T08:27:35.611864Z  INFO actix_web::middleware::logger: 172.20.0.5 "GET /collections/rag-qdrant HTTP/1.1" 404 92 "-
" "qdrant-client/1.13.2 python/3.11.11" 0.000409
qdrant-vector-db  | 2025-01-26T08:27:35.612829Z  INFO storage::content_manager::toc::collection_meta_ops: Deleting collection rag-qdrant
qdrant-vector-db  | 2025-01-26T08:27:35.612918Z  INFO actix_web::middleware::logger: 172.20.0.5 "DELETE /collections/rag-qdrant HTTP/1.1" 200 58
 "-" "qdrant-client/1.13.2 python/3.11.11" 0.000167
qdrant-vector-db  | 2025-01-26T08:27:35.614417Z  INFO storage::content_manager::toc::collection_meta_ops: Creating collection rag-qdrant
qdrant-vector-db  | 2025-01-26T08:27:35.637944Z  INFO actix_web::middleware::logger: 172.20.0.5 "PUT /collections/rag-qdrant HTTP/1.1" 200 57 "-
" "qdrant-client/1.13.2 python/3.11.11" 0.023616
qdrant-vector-db  | 2025-01-26T08:27:35.652448Z  INFO actix_web::middleware::logger: 172.20.0.5 "PUT /collections/rag-qdrant/points?wait=true HT
TP/1.1" 200 79 "-" "qdrant-client/1.13.2 python/3.11.11" 0.000784
qdrant-vector-db  | 2025-01-26T08:28:03.911038Z  INFO actix_web::middleware::logger: 172.20.0.4 "GET /collections/rag_qdrant/exists HTTP/1.1" 200 66 "-" "qdrant-client/1.13.2 python/3.11.11" 0.000387
qdrant-vector-db  | 2025-01-26T08:28:03.913743Z  INFO actix_web::middleware::logger: 172.20.0.4 "GET /collections/rag_qdrant/exists HTTP/1.1" 200 66 "-" "qdrant-client/1.13.2 python/3.11.11" 0.000072
qdrant-vector-db  | 2025-01-26T08:28:03.914621Z  INFO storage::content_manager::toc::collection_meta_ops: Creating collection rag_qdrant
qdrant-vector-db  | 2025-01-26T08:28:03.938203Z  INFO actix_web::middleware::logger: 172.20.0.4 "PUT /collections/rag_qdrant HTTP/1.1" 200 57 "-" "qdrant-client/1.13.2 python/3.11.11" 0.023654
qdrant-vector-db  | 2025-01-26T08:28:03.945781Z  INFO actix_web::middleware::logger: 172.20.0.4 "POST /collections/rag_qdrant/points/query HTTP/1.1" 200 66 "-" "qdrant-client/1.13.2 python/3.11.11" 0.00130
```

**Comment by lianhao** [comment]
Found the latest image of dataprep/retriever on redis also have the same issue, might be related to issue #1482

**Comment by letonghan** [comment]
Hi @lianhao , the root caused of dataprep has been located and fixed in [this PR](https://github.com/opea-project/GenAIComps/pull/1271). Please try again later after it is merged.

**Comment by letonghan** [comment]
The PR has been merged. Please try it out and contact for any other dataprep/retriever issues.

**Comment by lianhao** [comment]
@letonghan this Qrant issue still exists after this PR opea-project/GenAIComps#1271 is merged

**Comment by letonghan** [comment]
@lianhao  Do you have the log of backend with `LOGFLAG=true`?
The CI test of Qdrant passed, maybe there are some potential issues here.

**Comment by letonghan** [comment]
@lianhao The retriever issue of Qdrant is fixed in these two PRs: [PR 1289](https://github.com/opea-project/GenAIComps/pull/1289) and [PR 1555](https://github.com/opea-project/GenAIExamples/pull/1555).
Please try again using these branches or wait until PRs are merged.

**Comment by lianhao** [comment]
> [@lianhao](https://github.com/lianhao) The retriever issue of Qdrant is fixed in these two PRs: [PR 1289](https://github.com/opea-project/GenAIComps/pull/1289) and [PR 1555](https://github.com/opea-project/GenAIExamples/pull/1555). Please try again using these branches or wait until PRs are merged.

It's fixed. Thanks!
